### ISSUE TITLE
Build server URL is not always populated

### ISSUE THREAD

**Issue by dmackinnon** [jenkinsci/slack-plugin#124]
It seems that for some messages the base URL is getting included, but for others it's missing, which breaks the link.

For example:

![image](https://cloud.githubusercontent.com/assets/1126755/9495993/2e177a36-4bdc-11e5-96b7-68e343e137ef.png)

The working ones are being passed a correctly formatted link, so they're being linkified as expected. When it doesn't work, you only get the path to the specific build (eg /job/Coach/6665) which doesn't link.

**Comment by samrocketman** [comment]
That's odd behavior.  Can you give me an idea of how to replicate it?

**Comment by dmackinnon** [comment]
You're right, it does seem consistent. I tried to replicate it by creating a new job but wasn't able to. Here's a current job configuration:

![image](https://cloud.githubusercontent.com/assets/1126755/9568976/fb47c444-4f28-11e5-80da-351c7f28036e.png)

and our global config:

![image](https://cloud.githubusercontent.com/assets/1126755/9568979/263f5392-4f29-11e5-96a5-7b75941ad7fa.png)

**Comment by samrocketman** [comment]
Did you configure the affected jobs prior to upgrading the plugin at some point?  The job configurations and build URL settings are stored on a per job basis (I've found) so you might be able to fix it by doing the following.

1. Edit the configuration of the affected jobs. (Don't make any changes)
2. Save the job configuration.

This might update those settings.  Otherwise, you might need to edit the job XML on disk and reload configuration from disk.  I've found that the design of this plugin is fragile with how it saves and loads its configuration.

**Comment by dmackinnon** [comment]
Aha, that works! Looks like the failing jobs were the ones I had set up before I realized the base URL wasn't set.

It does seem like a bug that the settings aren't fetched from the current global config -- I'm not sure if that has to do with this plugin specifically though.

**Comment by samrocketman** [comment]
Agreed, I'm not sure what would be required to correct that.  As far as I'm concerned it could be done better by actually referring to the global configuration rather than saving global configuration in the Job XML.

I think the best course of action for addressing this bug is to create a new issue, describe the details of the configuration being saved in the job rather than referencing the global config, and link to this issue.  Then a contributor can work on the issue.

I don't actively develop this plugin.  I only maintain pull requests and releases for the user base in my spare time.

**Comment by dmackinnon** [comment]
Done, thanks for the help!

**Comment by samrocketman** [comment]
Thanks for your work.
