### ISSUE TITLE
Add "Accept untrusted SSL certificates option"

### ISSUE THREAD

**Issue by nevermindr** [jenkinsci/slack-plugin#155]
Add configuration parameter to support untrusted SSL certificates - for the cases when proxy is MITMing SSL connections.

**Comment by nevermindr** [comment]
@samrocketman 
added feature - it is based on CloseableHttlClient
depends on https://github.com/jenkinsci/slack-plugin/pull/156

**Comment by samrocketman** [comment]
Thanks for opening the issue as well as proposing a fix.  I'll still accept the proposed fix after code review as disabling SSL verification can have its uses when initially testing.

However, corporate MITM SSL proxies tend to have a certificate authority certificate so that all MITM connections can be verified as "trusted".  I recommend installing that CA cert in your Jenkins server so that one does not have to disable SSL verification.

Though, that might be a moot point because MITM SSL proxies break everything the public key infrastructure stands for (a different matter related to politics).

Thanks again.

**Comment by nevermindr** [comment]
I agree, it would be more clean to add CA cert to the JVM keystore - but it's not always possible because of politics/server infrastructure dependencies.

**Comment by timja** [comment]
Closed as probably not relevant any more
