### ISSUE TITLE
slack outgoing webhook isn't working

### ISSUE THREAD

**Issue by romanblachman** [jenkinsci/slack-plugin#218]
it looks that when setting up an external webhook for Slack isn't working if you do not specify an extra "/" in the webhook path.
for example, if the webhook endpoint is: slackwebhook
in order to access the webhook you need to specify an extra "/": https://dev-jenkins.company.com/%2Fslackwebhook/

it looks like it is caused do to getUrlName() method adding an extra "/" in front of the defined webhook endpoint name.

**Comment by samrocketman** [comment]
cc @dpires

**Comment by dpires** [comment]
The trailing slash requirement is documented in the help section for the url. I will however take a look at why it was required. From memory I don't think I could get the integration tests to run without it.

**Comment by samrocketman** [comment]
I don't think the root of the issue is the trailing slash but the prepended `%2F` (which is a URL encoded `/`).  e.g.

```
/%2Fslackwebhook/ == //slackwebhook/
```

That's my understanding.

**Comment by fwal** [comment]
Unsure about the status of this issue but I'm having no problems like this.

My setup:
- Jenkins `2.17`
- Slack plugin `2.0.1`
- Endpoint: `myendpoint`
- Slack web hook url: `http://myjenkins.com/myendpoint/`

**Comment by anderspikas** [comment]
I have the exact same problem as @romanblachman, on Slack plugin 2.2, Jenkins 2.75.
So, I think this issue was closed prematurely. I also need to add the extra %2F in the URL configured in `Outgoing webhooks` in Slack, e.g. `https://dev-jenkins.company.com/%2Fslackwebhook/`.
I looked at the unit tests, e.g. `WebhookEndpointTest#testListProjects` and noted that the test URLs end in e.g. `/jenkins/webhook`, because the site is configured to have `/jenkins` in the URL, not just the bare hostname. Maybe the unit tests pass because of the extra `/jenkins`?
