### ISSUE TITLE
buildServerUrl() missing in 2.1

### ISSUE THREAD

**Issue by gd-jroberts** [jenkinsci/slack-plugin#268]
With the upgrade to 2.1 the build server url field is missing from the global config screen and is breaking when publishers contains:

`slackNotifier {
                room('jenkins')
                notifyAborted(true)
                notifyFailure(true)
                notifyNotBuilt(true)
                notifyUnstable(true)
                notifyBackToNormal(true)
                notifySuccess(false)
                notifyRepeatedFailure(false)
                startNotification(false)
                includeTestSummary(false)
                includeCustomMessage(false)
                customMessage(null)
                buildServerUrl(null)
                sendAs(null)
                commitInfoChoice('NONE')
                teamDomain(null)
                authToken(null)
            }`

ERROR: (common.groovy, line 55) No signature of method: buildServerUrl() is applicable for argument types: (null) values: [null]
Possible solutions: teamDomain(), authToken(), room(), authTokenCredentialId(), sendAs(), startNotification(), notifyAborted(), notifyFailure(), notifyNotBuilt(), notifySuccess(), notifyUnstable(), notifyBackToNormal(), notifyRepeatedFailure(), includeTestSummary(), commitInfoChoice(), includeCustomMessage(), customMessage()

**Comment by kmadel** [comment]
Don't recognize that format - is this a FreeStyle job or a Pipeline job

**Comment by gd-jroberts** [comment]
It is a pipeline job: https://gist.github.com/gd-jroberts/2e3482040f6dce72d8decaa8ce1abeb5

**Comment by MichaelPereira** [comment]
@gd-jroberts : It looks like this property was [simply removed](https://github.com/jenkinsci/slack-plugin/commit/c4ee54c0a7827d59c170e68a8c4dac3aba6bf065#diff-f2606fe35028acac90e7e466dc4f5d4c) from the plugin since it's now using [another plugin](https://github.com/jenkinsci/display-url-api-plugin/blob/master/src/main/java/org/jenkinsci/plugins/displayurlapi/DisplayURLProvider.java) to display the server URL

**Comment by craigbye** [comment]
Can someone update the README for the slack plugin then?  The screenshots are still showing the buildSreverUrl configuraiton.   I am trying to determine how to configure the buildServerUrl with the new method with little success.  If the README were updated, perhaps I could.

**Comment by igostavro** [comment]
How and where do we specify the Build Server URL? The 'Open' links pushed to slack now have now point to 'unconfigured-jenkins-location/job/<etc...>'

**Comment by kerber** [comment]
Just to give some context on this, it looks like [#245](https://github.com/jenkinsci/slack-plugin/pull/245#issuecomment-242354743) and [192](https://github.com/jenkinsci/slack-plugin/issues/192) refer to this being removed, as it is now pulled from the Jenkins global configuration.

If your links aren't working, go to **Manage Jenkins > Configure System** and set **Jenkins URL**

**Comment by samrocketman** [comment]
Thanks for the context.  Since this isn't a bug it is ripe for closing.

**Comment by washingtoneg** [comment]
Coming late to the party, but I found https://github.com/chef-cookbooks/jenkins/issues/266#issue-42920303 helpful in my case and wanted to help others who may navigate to this thread in the future.

Essentially, if you are configuring Jenkins via some sort of configuration management system
and you have an issue where  'Open' links pushed to slack now point to 'unconfigured-jenkins-location/job/<etc...>', then it's not as simple as:

> If your links aren't working, go to **Manage Jenkins** > **Configure System** and set **Jenkins URL**

 You'll want to make sure that you have a `jenkins.model.JenkinsLocationConfiguration.xml` file stored on disk. You can use the code in the comment that I linked to generate this file. You'll need to restart Jenkins (or have the service come up with this config in place) since this and some other configs can't reloaded from disk (there is an [open issue](https://issues.jenkins-ci.org/browse/JENKINS-24734) about this).
