### ISSUE TITLE
How to create Credentials "Secret text"

### ISSUE THREAD

**Issue by mannv** [jenkinsci/slack-plugin#270]
I use 
Jenkins: **2.19.4**
Slack Notification Plugin: **2.1**

![secret](https://cloud.githubusercontent.com/assets/22742444/20952710/ecc5f75a-bc60-11e6-8ae3-aaaca1e46712.png)

How do I get it? **Secret**

I tried setup
![vl](https://cloud.githubusercontent.com/assets/22742444/20952767/4ed27982-bc61-11e6-870e-0fd8debea4a2.png)

**Comment by mannv** [comment]
@kmadel Please!

**Comment by dgoradia** [comment]
@mannv I think you either specify token or the credential id, not both.

**Comment by vinhtvu2** [comment]
If you specify both, the Integration Toekn Credential ID will take preference.

You create the slack-token ID by going to: 
Jenkins > Credentials > System > Global Credentials (or whatever group you want to have access or your access allow) > Add Credentials.

Then you add a "Secret Text", and give it an ID and description and put the token in the "secret" field. That's what you'll be using / selecting in the Integration Token Credential ID.

**Comment by shailleshtannu** [comment]
I'm able to see one extra parameter in this configuration, might be because of the update as below: 
![image](https://cloud.githubusercontent.com/assets/12457567/26520127/1f1ad97c-42ea-11e7-9498-96122ef9dac8.png)

If my url on stack is "shailesh.slack.com" is this to be considered as "Base URL" if so then what is "team sub-domain"?

I'm specifying the channel by #.... and not by the channel link.
I'm passing "Integration Token Credentials ID" and not the Integration Token.

I'm unable to get the test successful!

Can someone please help me!

Many Thanks,
Best Regards,
Shaillesh

**Comment by timja** [comment]
please open a new issue if you're still having problems..
