### ISSUE TITLE
Can't use environment variables in blue ocean Send slack message.

### ISSUE THREAD

**Issue by tommyboys0107** [jenkinsci/slack-plugin#370]
Hello!
I am using Send slack message in the blue ocean like the image below.
![default](https://user-images.githubusercontent.com/8335755/37757873-5013efba-2de9-11e8-9dee-b46ae93153be.png)

But I always get results that I don't expect.
![default](https://user-images.githubusercontent.com/8335755/37757977-a7682902-2de9-11e8-8708-4460458cf453.png)
Is that a normal behavior when using blue ocean? 
How can I fix it? Thanks!

**Comment by Randagio13** [comment]
I have the same problem.

**Comment by timja** [comment]
does `${env.BUILD_TAG}` work @Randagio13 ?
What does blue ocean generate when it commits the Jenkinsfile back to the repo?

**Comment by ZebraFlesh** [comment]
Apparently you have to do the quoting for Blue Ocean. So if you're trying to set the `channel` value to the `SLACK_SEND_CHANNEL` environment variable, the value you have to use in the Blue Ocean UI is `"${env.SLACK_SEND_CHANNEL}"`. This seems to generate the correct value in the generated Jenkinsfile.

**Comment by ZebraFlesh** [comment]
So that works for the `channel` value, but not the `message` value. Using an unquoted value of `STARTED: Job ${env.JOB_NAME} [${env.BUILD_NUMBER}] (${env.BUILD_URL})` Blue Ocean was generating this groovy:
```
message: 'STARTED: Job ${env.JOB_NAME} [${env.BUILD_NUMBER}] (${env.BUILD_URL})'
```

I tried explicitly specifying quotes (`"STARTED: Job ${env.JOB_NAME}..."` and `STARTED: Job "${env.JOB_NAME} [${env.BUILD_NUMBER}] (${env.BUILD_URL})"`), but that didn't work. I had to manually edit the Jenkinsfile output from Blue Ocean to fix the quoting. After that, it seemed to stick and survived multiple edits.

**Comment by timja** [comment]
It's nothing to do with this plugin anyway, we just use standard databinding.
Raise it as an issue with blue ocean
