### ISSUE TITLE
Credential ID lookup does not include credentials in Cloudbees folders

### ISSUE THREAD

**Issue by krajewf** [jenkinsci/slack-plugin#500]
When running jobs in folder, credentials defined in the folder are not found, only credentials defined in the root credentials store. Possibly because StandardSlackService is using Jenkins.get() for Credential lookup instead of maybe something like the parent item of the current job.

**Comment by tssingkofer** [comment]
Starting with v2.4, there was a change to what credentials would appear in the listBox for FreeStyle jobs merged with this pull request: 
https://github.com/jenkinsci/slack-plugin/pull/372/files

After the change, the plugin began using the context of the job for populating the available credentials in the listBox rather than the overall scope of the Jenkins instance. As @krajewf mentioned, in the StandardSlackService the lookupCredentials call is still referring to the top level scope of Jenkins ```Jenkins.get()``` to find credentials, so it doesn't find any folder level credentials at runtime even if the user was able to select it in the job configuration.
https://github.com/jenkinsci/slack-plugin/blob/8b04f771fdf8ee565bedbb9843a911552a9fd8e6/src/main/java/jenkins/plugins/slack/StandardSlackService.java#L202
I believe a similar change is needed here to use the context of the job in the credential lookup.

**Comment by timja** [comment]
Fixed in https://github.com/jenkinsci/slack-plugin/pull/541
