### ISSUE TITLE
Open to PR with Additional Logging?

### ISSUE THREAD

**Issue by sghill** [jenkinsci/slack-plugin#508]
I'd like to add additional logging to this plugin to gain some insight around the decisions it's making to send notifications. I'm happy to submit a PR, but first I thought I'd ask: is that likely to be accepted?

For example, the logic in [ActiveNotifier.java#L123](https://github.com/jenkinsci/slack-plugin/blob/master/src/main/java/jenkins/plugins/slack/ActiveNotifier.java#L123) is quite complex. Occasionally we'll troubleshoot something like notifications not coming through for multiple failed builds in a row, only to realize the advanced setting 'Notify on Repeated Failure' was not checked. If there were logs we could look to when a question arose, it'd really shorten the troubleshooting process.

There are places where logs exist that I'd like to be more detailed as well. For example [ActiveNotifier.java#L182](https://github.com/jenkinsci/slack-plugin/blob/master/src/main/java/jenkins/plugins/slack/ActiveNotifier.java#L182) has
```java
logger.info("No change set computed...");
```
but this is in the context of a build, and it'd be really helpful to have that information present when troubleshooting a particular job:
```java
logger.info("No change set computed for $projectName#$buildNumber");
```

**Comment by casz** [comment]
Again I think office365 plugin does it best or at least tries to :smile:
https://github.com/jenkinsci/office-365-connector-plugin/blob/master/src/main/java/jenkins/plugins/office365connector/Office365ConnectorWebhookNotifier.java#L152

This could use a rewrite to use the parent class `Run` instead of `AbstractBuild`
https://github.com/jenkinsci/slack-plugin/blob/15aea132f852f7a57e9f6cddf7e67d1c25cc2def/src/main/java/jenkins/plugins/slack/ActiveNotifier.java#L180

**Comment by timja** [comment]
I'm scared to touch that code (also I don't use that functionality so I'm less likely to notice if something goes wrong there) but a PR would certainly be accepted that refactors it

@casz's example is much better code than the state this part of the code currently is in
