### ISSUE TITLE
support link unfurling

### ISSUE THREAD

**Issue by realtime-neil** [jenkinsci/slack-plugin#526]
Currently, URLs within the `message` are not "unfurled" in slack parlance. Is it possible to fix this from within the `slackSend` source code? If so, then consider this a feature request for the same.

**Comment by EricBartusch** [comment]
I've been looking into this for a little while.  If all the plugin was doing was sending regular messages, this would be trivial to add: just throw in `json.put("unfurl_links", "true")` around here: https://github.com/jenkinsci/slack-plugin/blob/4db73420bba292217582df9b9611997d4a1f3015/src/main/java/jenkins/plugins/slack/StandardSlackService.java#L167-L169

Unfortunately, everything the plugin sends to Slack ends up being in an attachment because of this: https://github.com/jenkinsci/slack-plugin/blob/4db73420bba292217582df9b9611997d4a1f3015/src/main/java/jenkins/plugins/slack/StandardSlackService.java#L124-L136

My thought is to add an optional parameter flag that, if set, does not end up creating the attachment at all and instead sends normal text so unfurling can actually occur.  I couldn't find a way to unfurl links in attachments, but it might be possible.  What do you think @timja?

-Eric

**Comment by timja** [comment]
Seems like it should work, as an attachment?
https://api.slack.com/docs/message-attachments#unfurling

https://api.slack.com/docs/message-link-unfurling#classic_unfurling

But if you can't make it work then sure sounds fine

**Comment by EricBartusch** [comment]
I came across those links when doing my own digging.  The first one talks about how Slack with automatically make an attachment out of a URL with unfurling, while the second gives examples on how to unfurl messages specifically.  There is a chat.unfurl endpoint, but I don't think it'd fit in with the plugin very well.  It's supposed to be used by apps who are subscribed to a `link_shared` event that then will do unfurling for up to five custom domains.

I'll take a stab at making the new parameter and see how it goes.
