### ISSUE TITLE
More flexible channel separator syntax

### ISSUE THREAD

**Issue by mcandre** [jenkinsci/slack-plugin#55]
The first time I used the Jenkins Slack plugin, I experienced trouble finding the right syntax for configuring a job to notify multiple Slack channels. In the future, could we increase flexibility?

* Comma separation (the current, undocumented syntax: `#chan1,#chan2,...`)
* Space separation (`#chan1 #chan2 ...`)
* Comma with space separation (`#chan1, #chan2, ...`)

**Comment by samrocketman** [comment]
Documenting it is a start.  It's likely better to account for 1 format and document it for the user rather than account for several syntax variations.  I'd say the desired contribution is for someone to submit a pull request documenting the field in the Slack plugin UI of Jenkins configurations.

I don't actively develop the plugin but you're welcome to submit a pull request!  I only maintain pull requests and releases.

**Comment by mcandre** [comment]
Perfect! Thank you
