### ISSUE TITLE
How to remove newlines ?

### ISSUE THREAD

**Issue by lewer** [jenkinsci/slack-plugin#592]
### Config 

- [x] Jenkins version : 2.176.1

- [x] Plugin version : 2.24

- [x] OS : Debian stretch 9.9

### Description
Hi,

When notifications are sent to Slack, the resulting message seems to have newlines approximately every 80 characters :

![Screenshot at 2019-06-26 14-52-12](https://user-images.githubusercontent.com/5017269/60181575-cac92280-9822-11e9-9ce4-01582c2fa93f.png)

Here's the code in the pipeline which sends the message : 
```
def slack_message = "$slack_message_prefix Ubuntu $ubuntu_version  #${env.BUILD_NUMBER} ${currentBuild.currentResult} after ${currentBuild.durationString.replace(' and counting', '')} (<${env.RUN_DISPLAY_URL}|See results>)"
slackSend color: "$color", message: "$slack_message" 
```

Is there a way to avoid these newlines ?

Thanks.

**Comment by EricBartusch** [comment]
The line wrapping is due to how Slack displays attachments.  By default, the plugin will send your text as an attachment so you can format and use the color properties.  If you want to avoid the wrapping, use `sendAsText: true` instead.  You lose the formatting and all the other benefits of attachments, but the line length is not cut off so early and you get link/media unfurling.

**Comment by tomasj** [comment]
Hi guys, pls were you able to resolve this line wrap problem somehow?

**Comment by Jahidul2543** [comment]
I am seeing the similar problem while sending message to slack from Kibana. Not sure how can we sendAsText: true while using Slack webhook as Kibana Alert Destination. If anyone has any lead that will be highly appreciated.
