### ISSUE TITLE
Doesn't support the Jenkins Inheritance plugin

### ISSUE THREAD

**Issue by mansona** [jenkinsci/slack-plugin#6]
There is a really great plugin that allows you to build an inheritance tree for your builds, but this notification plugin just doesn't work with it. 

I don't know the specific requirements for getting plugins to work with the inheritance plugin but I wanted to open this issue and cross post an issue from their repo to get a conversation started. 

Here is the repo for the plugin: https://github.com/i-m-c/jenkins-inheritance-plugin/

**Comment by samrocketman** [comment]
Based on the number of open issues in the inheritance plugin it doesn't appear to work with many plugins.  I'm not going to make any assumptions as to which plugin is at fault so I'll label this contributions welcome.

I don't actively develop this plugin.  I only maintain incoming pull requests.

**Comment by samrocketman** [comment]
If you would like to be invited to https://jenkins-slack-plugin.slack.com/ for testing then just ask.

**Comment by mansona** [comment]
I'm also assuming that the inheritance plugin won't work, and i'm not sure how active the project is. I personally think this could be closed as a "won't fix" but if you want to leave it open for contributions that's ok too :wink:

**Comment by samrocketman** [comment]
No harm in leaving it open as contributions welcome.  Technically every open issue in this project is "won't fix" because I don't actively develop this project.  However, users of this plugin a kind enough to donate their time and create pull requests.  So to honor that I am willing to donate enough of my time to merge their pull requests and attempt to release on a monthly schedule.

**Comment by nevermindr** [comment]
As inheritance plugin supports publishers, `slack-plugin` should be compatible with it starting from `2.0-SNAPSHOT` version.
I did a short test by creating parent/child inheritance jobs and it works more or less.

There is a strange behaviour - like if "startNotification" paremeter is unset in child plugin but is enabled in parent - it will still send startNotifications when building child.

Also settings migration is not working but this does not seem to be an issue because it was not possible to use `slack-plugin` with inheritance before `2.0-SNAPSHOT` version.

@samrocketman: so this functionality is now at least testable. Should we add it to 2.0/2.1 milestone?

**Comment by samrocketman** [comment]
Sure we can set it as a goal for fixing since you feel it applies.
