### ISSUE TITLE
Turn on slack-plugin Logging?

### ISSUE THREAD

**Issue by pauljsolomon** [jenkinsci/slack-plugin#9]
I installed your plugin and it seems to do nothing.  There are no logs generated on my jenkins box.  Is there a way to turn on logging for this plugin, so I can debug the problem?

**Comment by ChrisDunneFlyPay** [comment]
I am also having the same problem. As noted above as well the link to the plugin, from the manage plugins page also doesn't work.

Jenkins version 1.598

**Comment by samrocketman** [comment]
If you go to the integrations page on slack they outline all of the steps for setting the plugin up in Jenkins.

**Comment by ChrisDunneFlyPay** [comment]
I went though the guide again and solved my issue. I had to state the slack channel in the project config. I thought it would just use the default one I had set on Slack.com or in jenkins configuration settings.

**Comment by samrocketman** [comment]
It does use the global configuration if there's none stated for the project.  I've at least witnessed that testing with `1.7-SNAPSHOT` version. I've not used the stable version yet.  I'll be doing a release maybe later this week or by the weekend.  Depends on my time and ability to figure out Jenkins releases (which are well documented I believe).

**Comment by samrocketman** [comment]
The next release will have better logging.  Since this is an old issue I'm going to close it.  Feel free to open a new issue after [testing the next release](https://github.com/jenkinsci/slack-plugin/milestones) if you feel your issue isn't resolved.

I do not actively develop this plugin.  I will be maintaining pull requests and releases from now on.  Contributions are welcome if you implement this missing feature!
