### ISSUE TITLE
Slack App "Jenkins CI" is nowhere mentioned. Instead, steps are provided to create custom App

### ISSUE THREAD

**Issue by Padmahas** [jenkinsci/slack-plugin#984]
### Describe your use-case which is not covered by existing documentation.

Accidentally I found out an App named "Jenkins CI" in my office's Slack channel which was installed from one of my senior developer, who no longer works in our company.
1. I Googled around about that App.
2. From Slack, installed that app to the workspace to where I wanted to send slack notifications.
3. Once the app was added, some configuration instructions were auto generated in the Slack's website and followed it.
4. And used "slackSend" syntax

And it was so easy that I started getting slack notifications within 15 mins.
But if this was mentioned in this documentation, it would have been very easy, instead of creating our own App.

### Are you interested in contributing to the documentation?

Yes. especially, I want to add the above instructions mentioned.

**Comment by timja** [comment]
Its easy but half of the modern slack features don't work, the method you are using is whats known as a 'legacy integration' in Slack. It comes from before they had their app extensions when they built all the integrations into their own code base. They haven't added support for a number of features like blocks, file upload and possibly others.

A lot of user support has came from issues relating to that so that documentation was removed in favour of the approach that worked in all cases.

**Comment by Padmahas** [comment]
> Its easy but half of the modern slack features don't work, the method you are using is whats known as a 'legacy integration' in Slack. It comes from before they had their app extensions when they built all the integrations into their own code base. They haven't added support for a number of features like blocks, file upload and possibly others.
> 
> A lot of user support has came from issues relating to that so that documentation was removed in favour of the approach that worked in all cases.

So, building our own app is the best approach currently and going forward?

**Comment by timja** [comment]
Yes definitey

**Comment by Padmahas** [comment]
OK. Thank you @timja .
